apiVersion: 1

datasources:
  - name: Macro SQLite
    uid: macro-sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /data/macro.db